### ISSUE TITLE
[api] Add /admin/log route

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#807]
"Convenience" operations (these are always transient operations):
- [x] `GET /admin/log` (https://github.com/telefonicaid/fiware-cygnus/pull/1112)  
|__ TEST for `GET /admin/log` (https://github.com/telefonicaid/fiware-cygnus/pull/1130)
- [x] `PUT /admin/log?level=<level>` (https://github.com/telefonicaid/fiware-cygnus/pull/1114)  
|__ TEST for `PUT /admin/log?level=<level>` (https://github.com/telefonicaid/fiware-cygnus/pull/1130)

"General" operations (`transient` and `no transient` options)

- [x] `GET /v1/admin/log/appenders` (transient + no transient) (#1131)
- [x] `GET /v1/admin/log/appenders?name=<appender_name>` (transient + no transient) (#1131)
- [x] `GET /v1/admin/log/loggers` (transient + no transient) (#1136)
- [x] `GET /v1/admin/log/loggers?name=<logger_name>` (transient + no transient) (#1136)
- [x] `PUT /v1/admin/log/appenders?name=<appender_name> -d { json with appender data } ` (transient + no transient)  (#1167)
- [x] `PUT /v1/admin/log/loggers?name=<logger_name> -d { json with logger data } ` (transient + no transient) (#1168)
- [x] `POST /v1/admin/log/appenders?name=<appender_name> -d { json with appender data } ` (transient + no transient) (#1173)
- [x] `POST /v1/admin/log/loggers?name=<logger_name> -d { json with logger data } ` (transient + no transient) (#1174)
- [x] `DELETE /v1/admin/log/appenders` (transient + no transient) (#1157)
- [x] `DELETE /v1/admin/log/appenders?name=<appender_name>` (transient + no transient) (#1157)
- [x] `DELETE /v1/admin/log/loggers` (transient + no transient) (#1160)
- [x] `DELETE /v1/admin/log/loggers?name=<logger_name>` (transient + no transient) (#1160)

- [ ] General documentation for all implemented methods

**Comment by frbattid** [comment]
Because there are several configuration files, a second level on the route must be added:

* `/v1/configuration/agent`
* `/v1/configuration/instance`
* `/v1/configuration/log4j`

**Comment by frbattid** [comment]
There is a requirement form IoT platform about standardizing the way the log level is changed:

`POST /admin/log?level=info`

By calling to the above API method may be a redirection to:

`POST /v1/configuration/log4j?param=flume.root.logger&value=<level>,<appender>`

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/891 (`PUT /admin/log?level=<log_level>`)

**Comment by pcoello25** [comment]
GET method will change. 
- GET /admin/log will print the current log level
- GET /admin/log?verbose=true will print the actual logs

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1108 (GET /admin/log & GET /admin/log?verbose=true|false)

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1109 (GET /admin/log with `verbose` and `transient`parameters)

**Comment by pcoello25** [comment]
Partially implemented in #1112 (`Convenience` GET method)

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1114 (PUT logging level method -> Convenience)

**Comment by pcoello25** [comment]
Partially implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1130 (TEST for convenience methods)

**Comment by pcoello25** [comment]
Partially implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1131 (GET appenders: GET all & GET by name)

**Comment by pcoello25** [comment]
Partially implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1136 (GET loggers: GET all & GET by name)

**Comment by pcoello25** [comment]
Partially implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1157 (DELETE appenders)

**Comment by pcoello25** [comment]
Partially implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1160 (DELETE loggers)

**Comment by pcoello25** [comment]
Partially implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1167 (PUT appenders)

**Comment by pcoello25** [comment]
Partially implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1168 (PUT loggers)

**Comment by pcoello25** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1173 (POST appenders)

**Comment by pcoello25** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1174 (POST loggers)

**Comment by pcoello25** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1185 (documentation)
