### ISSUE TITLE
[api] Add /admin/configuration/agent/path/to/agent.conf route

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#893]
- [x]  GET `/admin/configuration/agent/path/to/agent.conf` (gets all the parameters) #1070 
- [x]  Test for GET all parameters  https://github.com/telefonicaid/fiware-cygnus/pull/1085
- [x]  GET `/admin/configuration/agent/path/to/agent.conf?param=<param_name>`  #1072 
- [x]  Test for GET one parameter https://github.com/telefonicaid/fiware-cygnus/pull/1085
- [x]  POST `/admin/configuration/agent/path/to/agent.conf?param=<param_name>&value=<param_value>`  #1080
- [x]  Test for POST one parameter https://github.com/telefonicaid/fiware-cygnus/pull/1085
- [x]  PUT `/admin/configuration/agent/path/to/agent.conf?param=<param_name>&value=<param_value>`  #1077
- [x]  Test for PUT a parameter https://github.com/telefonicaid/fiware-cygnus/pull/1085
- [x]  DELETE `/admin/configuration/agent/path/to/agent.conf?param=<param_name>`  #1081 
- [x]  Test for DELETE a parameter https://github.com/telefonicaid/fiware-cygnus/pull/1085
- [x]  Document all API methods #1082 
- [x]  Check for agent file name (must start with `agent_`) https://github.com/telefonicaid/fiware-cygnus/pull/1086

**Comment by frbattid** [comment]
As discussed offline, we hould support both `/v1/admin/...` and `/admin/...`.

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1070 (GET all parameters)

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1072 (GET a single parameter)

**Comment by pcoello25** [comment]
Partially implemented in #1077 (PUT a single parameter)

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1080 (POST a single parameter)

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1081 (DELETE a single parameter)

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1084 (Check for agent file name)

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1082 (Documentation with all the methods)

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1085 (Test for all methods)

**Comment by pcoello25** [comment]
Partially implemented in #1086 (Test for agent configuration file name)

**Comment by pcoello25** [comment]
All the task have been completed, closing issue :muscle:
